apiVersion: apps/v1
kind: Deployment
metadata:
  name: borrow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: borrow
  template:
    metadata:
      labels:
        app: borrow
    spec:
      containers:
        - image: jp4861/borrow:2021-11-12-23-05-56
          name: borrow
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://fanny.db.elephantsql.com:5432/sewztpca
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: sewztpca
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: jviqrny5vLJYogFEeyBhAr7daifOAiwB
          ports:
            - containerPort: 5556
              name: server
              protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: borrow
spec:
  type: LoadBalancer
  ports:
    - port: 5556
      protocol: TCP
      targetPort: server
  selector:
    app: borrow