kumuluzee:
  name: borrow-system
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:/
    http:
      port: 5556
  datasources:
    - jndi-name: jdbc/ItemDS
      connection-url: jdbc:postgresql://fanny.db.elephantsql.com:5432/sewztpca
      username: sewztpca
      password: jviqrny5vLJYogFEeyBhAr7daifOAiwB
      max-pool-size: 1
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ItemDS

rest-properties:
  maintenance: false