kumuluzee:
  name: recommendation-system
  version: 1.0.0
  env:
    name: dev
  server:
    base-url: http://localhost:/
    #base-url: http://prpo-priporocilni-sistem-prpo-priporocilni-sistem.apps.us-west-1.starter.openshift-online.com/v1/priporocila
    http:
      port: 3333
  datasources:
    - jndi-name: jdbc/ItemDS
#      connection-url: jdbc:postgresql://database:5432/rentarich
      connection-url: jdbc:postgresql://localhost:5432/rentarich
      username: postgres
      password: postgres
      max-pool-size: 20
